name: kezanat_alsama
description: for find jobs

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0+18

environment:
  sdk: ">=3.0.0 <=3.5.1"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localization: ^0.2.1
  localization: ^2.1.0  
  intl: ^0.19.0
  flutter_svg: ^1.0.3

  modal_bottom_sheet: ^2.0.1
  provider: ^6.0.0
  visibility_detector: ^0.3.3
  simple_gradient_text: ^1.2.4
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  lucide_icons: ^0.105.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.18.2+1
  permission_handler: ^11.3.0
  path_provider: ^2.0.14
  solar_calculator: ^1.0.3
  uni_links: ^0.5.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  dropdown_button2: ^2.3.9
  injectable: ^2.3.0
  skeletonizer: ^1.4.2
  cached_network_image: ^3.3.1
  flutter_timezone: ^1.0.8
  synchronized: ^3.1.0+1
  sizer: ^2.0.15
  external_path: ^1.0.3
  dio: ^5.3.2
  collection: ^1.18.0
  animated_size_and_fade: ^3.0.1
  eva_icons_flutter: ^3.0.2
  get: ^4.3.8
  percent_indicator: ^3.4.0
  dotted_border: ^2.0.0+1
  timeago: ^3.1.0

  sidebarx: ^0.17.1

  sidebar_with_animation: ^0.0.3
  
  

dev_dependencies:

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator:
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/fonts/scheherazade/
    - assets/lottie/
    - assets/docs/
    - assets/docs/books/
    - assets/docs/dua/
    - assets/sound/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Somar
      fonts:
       
      
        - asset: assets/fonts/somar/SomarSans-Bold-edited.otf
          weight: 900
        - asset: assets/fonts/somar/SomarSans-Bold-edited.otf
          weight: 800
        - asset: assets/fonts/somar/SomarSans-Bold-edited.otf
          weight: 700

        - asset: assets/fonts/somar/SomarSans-Medium-edited.otf
          weight: 600
        - asset: assets/fonts/somar/SomarSans-Medium-edited.otf
          weight: 500


        - asset: assets/fonts/somar/SomarSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/somar/SomarSans-Regular.ttf
          weight: 300
    - family: authman
      fonts:
       
      
        - asset: assets/fonts/authman.ttf
          weight: 500
    - family: muhakik
      fonts:
       
      
        - asset: assets/fonts/muhakik.ttf
          weight: 500      
       
    - family: Dywan
      fonts:
       
      
        - asset: assets/fonts/dywan.ttf
    - family: Kufy
      fonts:
       
      
        - asset: assets/fonts/kufy.ttf
    - family: Am
      fonts:
       
      
        - asset: assets/fonts/am.ttf

    - family: basmala
      fonts:
        - asset: assets/fonts/basmala.otf

    

    - family: scheherazade
      fonts:
        
        - asset: assets/fonts/scheherazade/ScheherazadeNew-SemiBold.ttf
          weight: 700

        - asset: assets/fonts/scheherazade/ScheherazadeNew-Regular.ttf
          weight: 500     


        

       
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
